### ISSUE TITLE
Parse @username to a real username link within dAmn.

### ISSUE THREAD

**Issue by aaronpearce** [graulund/superdAmn#16]
Dunno if this one is possible?

**Comment by joshtwo** [comment]
Depends on what you intend to do. If you use the same DiFi requests and possibly include some of the JS via DWait you may be able to imitate the Comment Writer interface.

**Comment by Trezoid** [comment]
Imitating the writer interface is not that viable (writer is a huge, awful beast that isn't particularly viable in dAmn). It would be simpler to just convert ` @username ` to ` :devusername: ` and let the back-end handle the actual linkification

**Comment by aaronpearce** [comment]
Was going to do the route that @Trezoid suggests, `@username` -> `:devusername:`, issue could be if this fails?

**Comment by Trezoid** [comment]
Worst case scenario is they get `:devusername:` without wanting it, but the number of times someone types a bare `@username` without wanting a DA username is pretty tiny.

**Comment by joshtwo** [comment]
That was my very first idea but if the entire file had to be included that'd probably be impractical.

**Comment by aaronpearce** [comment]
See #18
